[package]
name = "blinded_query_proof"
type = "bin"
authors = [""]

[dependencies]
ecrecover = { path = "../vendor/ecrecover" }
babyjubjub = { git = "https://github.com/TaceoLabs/oprf-nr", tag = "v2.0.0", directory = "babyjubjub" }
oprf = { git = "https://github.com/TaceoLabs/oprf-nr", tag = "v2.0.0", directory = "oprf" }
