name: E2E test

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:

permissions:
  contents: read

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: E2E-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@e2a55d2ffb04f378e9626c28d38b36d230d1e12f # master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
      - run: cd contracts && forge build
      - run: |
          curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/next/barretenberg/bbup/install | bash
          echo "${HOME}/.bb" >> $GITHUB_PATH
          ${HOME}/.bb/bbup -v 5.0.0
      # - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - name: E2E-Test
        run: bash local-setup.sh test
