name: Rust Tests

on:
    push:
        branches:
            - main
        tags-ignore:
            - v*
    pull_request:

permissions:
    contents: read

env:
    # incremental builds are slower and don't make much sense in ci
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: FULL

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  submodules: recursive
            - uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # master
              with:
                  toolchain: stable
            - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
            - name: Unit & Integration Tests
              run: cargo test --workspace --profile ci-dev --all-features --all-targets
